### ISSUE TITLE
vendor bootstrap.php

### ISSUE THREAD

**Issue by timglabisch** [beberlei/fiddler#10]
When i try to define this as vendor, i get the following error by using the autoloader:

      "vendor/symfony/phpunit-bridge"

And the error:

      Warning: require(/Users/***/vendor/symfony/phpunit-bridge/bootstrap.php): failed to open stream: No such file or directory in   /Users/***/fiddlerDemo/components/project_c/vendor/composer/autoload_real.php on line 54

But:

      "vendor/symfony/symfony"

works fine for me

**Comment by asm89** [comment]
@timglabisch Any chance you can put up a repository/gist with the files etc to reproduce this case?

**Comment by timglabisch** [comment]
i am going to close this issue. seems not reproduce able.
