### ISSUE TITLE
provide the link of a FOSS project in which this is used

### ISSUE THREAD

**Issue by cordoval** [beberlei/fiddler#11]
would be nice to see an example to easy adoption for this tool

so that we can test ourselves and see the benefits first hand and

also copy paste and adapt the configuration to our internal or other FOSS projects.

Thanks!

**Comment by beberlei** [comment]
This will need to wait for an OS project actually using it. I am currently only using it in proprietary projects.

**Comment by DHager** [comment]
I think this could dovetail with integration testing, using a demo app. Since storing git repositories inside one-another may be problematic, why not some scripts to create/teardown a fake "AcmeCo" project?
