### ISSUE TITLE
How do you install it ?

### ISSUE THREAD

**Issue by Gregoriz** [beberlei/fiddler#15]
Hello there,

Your tool seems to be responding to my needs. But actually, there is no indications about how installing it.

Is there an easy way to do it ? Like the same way you install composer, or event like https://github.com/mybuilder/conductor/tree/master/examples/todo ?

**Comment by tolry** [comment]
It seems there is no build provided yet, `composer global require ...` doesn't work also, due to fiddler not being listed at packagist.

Easiest way I got it running yet is by building it manually (requires ant)

```sh
$ git clone https://github.com/beberlei/fiddler.git
$ cd fiddler
$ composer install
$ ant build
# you now have a fiddler.phar that you can put anywhere in your PATH
```

I hope this helps.

**Comment by asm89** [comment]
@beberlei 
- any specific reason fiddler is not on packagist?
- how about attaching the phar to the releases?

**Comment by beberlei** [comment]
You install this via PHAR from the release page, the last one being https://github.com/beberlei/fiddler/releases/tag/v0.5
