### ISSUE TITLE
Package dependency with lowercase name and mixed case path results in "Requiring non existant package" error

### ISSUE THREAD

**Issue by timroberson** [beberlei/fiddler#16]
Consider the following directory structure:
```
├── myapp
│   └── fiddler.json
├── composer.json
```
In `composer.json`:
```
{
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1.*"
    }
}
```
In `myapp/fiddler.json`:
```
{
    "deps": [
        "vendor/laravel/framework"
    ],
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        }
    }
}
```
This results in:
```
[RuntimeException]
  Requiring non existant package 'vendor/jeremeamia/superclosure' in 'myapp'.
```
My app includes `laravel/framework` which in turn includes `jeremeamia/superclosure`. The path to `jeremeamia/superclosure` is `vendor/jeremeamia/SuperClosure`. It seems that this can be resolved by changing:
```
$packages['vendor/' . $name] = $fiddleredComposerJson;
```
to:
```
$packages['vendor/' . strtolower($name)] = $fiddleredComposerJson;
```
in `Fiddler\Build`, but I'm not familiar enough with the package yet to know if this causes other issues. Does anyone have any thoughts on this issue? Thanks!

**Comment by asm89** [comment]
@timroberson Can you create a pull request?

**Comment by beberlei** [comment]
This looks like a mistake in composer, i thought it requires everything to be lowercase. The proposed solution looks good.
