### ISSUE TITLE
Implement as composer plugin?

### ISSUE THREAD

**Issue by DHager** [beberlei/fiddler#22]
I know this is only used for internal proprietary stuff at the moment, but would it be *theoretically*-possible to implement it as a composer plugin, hooking it up to composer's update/autoload/install events? 

I'm having a similar problem at my workplace, where we have some projects that I want to keep separate from a test-suite/reuse perspective, but where people are having problems with the multi-repository approach.

**Comment by beberlei** [comment]
@DHager Yes that is possible and it makes absolute sense to do this.

In the root of your project, you would do "composer update" and then it would automatically call fiddler build afterwards. This is a great idea!

**Comment by asm89** [comment]
:+1: sounds like a great addition

**Comment by DHager** [comment]
Since there's no "fundamentally different paradigm" issues, I'm willing to try developing it, but first I need to figure out a good test-harness with "regular" fiddler and some mock AcmeCo repository.
