### ISSUE TITLE
May be some improvements in documentation

### ISSUE THREAD

**Issue by harikt** [beberlei/fiddler#3]
Hi @beberlei , 

I downloaded the fiddler.phar file . And tried with what I understood.

I created the `fiddler.json` like 

```json
{
    "deps": [
        "vendor/cakephp/"
    ],
    "autoload": {
        "psr-0": {
            "Foo\\":"src/"
        }
    }
}
```

I have a dependency on `cakephp/orm` on the composer.json . Is there anything I missed for the fiddler seems not changing anything. Is that due to the bug you mentioned on the commit ?

Or may be I am missing the whole point on the docs :-/ .

**Comment by beberlei** [comment]
@harikt please download v0.2, the first one was utterly broken.

**Comment by beberlei** [comment]
@harikt You should also remove the trailing slash in the `deps`

**Comment by harikt** [comment]
@beberlei may be you forgot to rename as phar :) . It is tar.gz now .

**Comment by harikt** [comment]
Hm, it seems you made phar and then tar.gz :/ .

**Comment by harikt** [comment]
```bash
$ php ../fiddler/fiddler.phar build
Building fiddler.json projects.
 [Build] 
                                                          
  [RuntimeException]                                      
  Requiring non existant package 'vendor/cakephp' in ''.  
                                                          
build

[php:5.5.9-system]\n$ ls vendor/cakephp 
collection  core  database  datasource  event  orm  utility  validation
[php:5.5.9-system]\n$
```

Any idea on the error ?

**Comment by beberlei** [comment]
@harikt Its not a package name, because there is no composer.json in it. maybe 'vendor/cakephp/orm' ?

**Comment by harikt** [comment]
@beberlei getting ` /vendor does not exist and could not be created.`

**Comment by beberlei** [comment]
@harikt where is your `fiddler.json` located? Sorry not sure what this is.

**Comment by harikt** [comment]
```bash
$ pwd
/var/www/github.com/harikt/cakephp3

$ ls
composer.json  composer.lock  fiddler.json  src  vendor

$ ls vendor 
autoload.php  cakephp  composer

$ ls vendor/cakephp 
collection  core  database  datasource  event  orm  utility  validation

$ ls vendor/cakephp/orm 
Association                      Behavior              EagerLoadable.php  Marshaller.php  Rule
AssociationCollection.php        Behavior.php          EagerLoader.php    Query.php       RulesChecker.php
Association.php                  BehaviorRegistry.php  Entity.php         README.md       Table.php
AssociationsNormalizerTrait.php  composer.json         Exception          ResultSet.php   TableRegistry.php
```

**Comment by beberlei** [comment]
@harikt Thats not the way it is supposed to work. You should have subcomponents, i.e.

    |- components
    | |- foo
    |   \-fiddler.json
    | \- bar
    |   \-fiddler.json
    |- composer.json
    \- vendor

**Comment by harikt** [comment]
Hm, so I suppose we need to run `php fiddler.phar` from `foo` and `bar` folders ?

And this will be moved to vendor folder ? or a vendor is created ?

**Comment by beberlei** [comment]
@harikt No it recursivly searches and finds all fiddler.json files.

**Comment by beberlei** [comment]
I close for now

**Comment by harikt** [comment]
sure. I will try once again. Holidays on the way :) .
