### ISSUE TITLE
what is the difference to gitsplit?

### ISSUE THREAD

**Issue by cordoval** [beberlei/fiddler#7]
I read the blog post today of fiddler and was wondering what is the difference to
https://github.com/Gitsplit/gitsplit

I guess long term git split is the current subtree splitter, but there seems to be a very good
idea on fiddler which is the reuse of the composer autoloading.

So I think some features that automate the handling of the subtree split can be introduced here as well?

**Comment by beberlei** [comment]
@cordoval The goal with fiddler is not necessarily open sourcing the packages. Git split is a tool that is necessary to make Composer/Packagist happy in OSS land. 

With a Gitsplit model like Symfony, you have a global composer.json and then many small ones. The global one defines an autoloader overriding the small ones that are not used in single repository mode. You have to duplicate all the autoload and dependency definitions with the potential to introduce errors.

With Fiddler you only define each package once, not again globally and then manage the dependencies between them.

**Comment by cordoval** [comment]
Thanks for your response Benjamin. yeah gitsplit is a long but it is a symfony project but it is not mature enough and i don't think it does the same functionality as fiddler. I will try to introduce it there because i think it makes sense after i play with fiddler a bit more, or i shall say after i fiddle with it a bit more :older_man:  Thanks.
